version: '3.9'

services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passroot
      - MYSQL_PASSWORD=pass
      - MYSQL_USER=user
      - MYSQL_DATABASE=db_jee